log_path: logs
bert_model: beomi/kcbert-base
train_data_path: data/kcbert/train_data_12000.txt
val_data_path: data/kcbert/val_data_12000.txt
test_data_path: data/kcbert/test_data_12000.txt
max_len: 128
train_batch_size: 64
eval_batch_size: 32
dropout_rate: 0.1
gpus: 1
distributed_backend: ddp