task: ko_spacing
log_path: logs
bert_model: monologg/kobert
train_data_path: data/train.txt
val_data_path: data/val.txt
test_data_path: data/test.txt
max_len: 128
train_batch_size: 192
eval_batch_size: 128
dropout_rate: 0.1
gpus: 1
# distributed_backend: ddp
strategy: dp